vidly_Django/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
     path('', views.index, name='index'),
     path('<int:movie_id>',views.details, name='details')
]

vidly_Django/vidly_Django/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views
movie_resource=MovieResource()

# app_name = "vidly"

urlpatterns = [
    path('', views.Home, name='home'),
    path('admin/', admin.site.urls),
    path('movies/',include('movies.urls')),
    path('api/', include(movie_resource.urls))
]

vidly_Django/api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.

class MovieResource(ModelResource):
     class Meta:
          queryset = Movie.objects.all() # It will return a query 
          resource_name = 'movies'
          excludes = ['date_created']

vidly_Django/movies/models.py
from django.db import models
from django.utils import timezone
# Create your models here.

class Genre(models.Model):
     name = models.CharField(max_length=255)

     def __str__(self):
          return self.name

class Movie(models.Model):
     title = models.CharField(max_length=255)
     release_year = models.IntegerField()
     number_in_stock = models.IntegerField()
     daily_rate = models.FloatField()
     genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
     date_created = models.DateTimeField(default=timezone.now)

vidly_Django/api/views.py
from django.shortcuts import render

# Create your views here.

vidly_Django/movies/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404
from .models import Movie


# Create your views here.
def index(request):
     movies=Movie.objects.all()
     return render(request,'movies/index.html', {'movies': movies})

def details(request, movie_id):
     movie = get_object_or_404(Movie,pk=movie_id)
     return render(request,'movies/details.html', {'movie':movie})
    
     """
     output=' , '.join([m.title for m in movies])
     #SELECT * FROM movies_movie
     Movie.objects.filter(relase_year=2004)
     #SELECT * FROM movies_movie WHERE ....
     Movie.objects.get(id=1)
     """

     # return HttpResponse(output)

vidly_Django/vidly_Django/views.py
from django.shortcuts import render

def Home(request):
     return render(request, 'home.html')

vidly_Django/movies/templates/movies/details.html
{% extends 'base.html' %} {% block content %}
<dl>
  <dt>Title</dt>
  <dd>{{ movie.title}}</dd>
  <dt>Genre</dt>
  <dd>{{ movie.genre}}</dd>
  <dt>Stock</dt>
  <dd>{{ movie.number_in_stock}}</dd>
</dl>
{% endblock %}

vidly_Django/movies/templates/movies/index.html
{% extends 'base.html' %} {% block content %}
<table class="table table-bordered table-hover">
  <thead>
    <th>Title</th>
    <th>Genre</th>
    <th>Stock</th>
    <th>Daily Rate</th>
  </thead>
  <tbody>
    {% for movie in movies %}
    <tr>
      <td>
        <a href="{% url 'movies:details' movie.id %}">{{ movie.title}}</a>
      </td>
      <td>{{ movie.genre }}</td>
      <td>{{ movie.number_in_stock }}</td>
      <td>{{ movie.daily_rate}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

vidly_Django/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />

    <title>Vidly</title>
  </head>
  <body>
    <nav class="navbar bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Vidly</a>
      </div>
    </nav>
    <main class="container">{% block content %} {% endblock %}</main>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

vidly_Django/templates/home.html
{% extends 'base.html' %} {% block content %}

<a href="{% url 'movies:index' %}">Movies</a>
{% endblock %}